import { InjectionToken } from '@angular/core';

export const AUTHENTICATION_SERVER_ROOT_URI = new InjectionToken('AUTHENTICATION_SERVER_ROOT_URI');
export const AUTHENTICATION_LOGIN_PAGE_URI = new InjectionToken('AUTHENTICATION_LOGIN_PAGE_URI');
export const AUTHENTICATION_INTERFACES = new InjectionToken('AUTHENTICATION_INTERFACES');
export const AUTHENTICATION_DROPDOWN_ITEMS = new InjectionToken('AUTHENTICATION_DROPDOWN_ITEMS');
export const AUTHENTICATION_LOGIN_PIPELINE = new InjectionToken('AUTHENTICATION_LOGIN_PIPELINE');